[project]
name = "cooked-lol"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "matplotlib",
    "plotly",
]

[project.optional-dependencies]
dev = ["black", "pyright"]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["cooked_lol*", "cooks*"]

[tool.pyright]
include = ["cooked_lol", "cooks"]
venvPath = "."
venv = "env"
pythonVersion = "3.11"
typeCheckingMode = "standard"
reportMissingTypeStubs = false
